### ISSUE TITLE
Should classes be prefixed with "now-"?

### ISSUE THREAD

**Issue by ldabiralai** [sky-uk/nowtv-styleguide#47]
Most components at the moment are prefixed with ```now-``` to scope them to the styleguide, but I've noticed a few recent ones are not. For example, the headers and the icons.

Should we be enforcing the ```now-``` prefix, and change the ones just mentioned to include this prefix?

**Comment by peter-mouland** [comment]
agreed - i reckon they should be

**Comment by peter-mouland** [comment]
there seems to be a few breaking changes around css that are needed (https://github.com/sky-uk/nowtv-styleguide/issues/48)

also the smacs v bem debate (ie.. buttons vs accordion)

Would be good to get all the changes done in single PR to minimise the number of breaking changes

**Comment by alexflorisca** [comment]
@peter-mouland @ldabiralai @rogerfranklin2 @ariley90 @alexjfno1 I've tagged you since you're most active in global discussions, this is obv open to all.

So we are blocked on loads of stuff and we might do some global work. Can we get a consensus on this and we can get some of these issues resolved...

1. BEM vs SMACCS
2. Prefix all classes with now-

For the record, I'm for BEM and prefixes.

**Comment by alexflorisca** [comment]
Speak now or be BEMified, I'm gona start on this shortly...

**Comment by ariley90** [comment]
We mentioned in the catch up yesterday that we need to decide on the BEN vs SMACSS's approach, I thought we agreed to have a separate session for discussing the pro's and con's of each? Personally I'm for SMACSS's over BEM and would be interested in understanding the reasons why we want to switch now. I don't want you to invest lots of time now if we don't swap to BEM.

**Comment by alexflorisca** [comment]
Yeah fair, just spoke to pete. I just had a look through the styleguide and I don't think it will take very long to BEM it. Since I've short of work, I was thinking of doing it on a branch, as an example and then we can compare and discuss it. Obviously will be happy to throw it away if the consensus is SMACCS.

**Comment by ariley90** [comment]
Yeah, maybe take 1 or 2 components and do it then I could the same in SMACSS in the coming days?

**Comment by peter-mouland** [comment]
be great to get a SMACCS branch too

**Comment by peter-mouland** [comment]
this has been on my mind and i'm actually going the other way and thinking about NOT have `now-` prefixes.

The reason is, although the style-guide is public, in reality it is only used by a few teams (True, this may grow in the future).  The style-guide is the source of truth for components, so lets go whole hog and instead of having `now-button` and `now-accordion`, lets just have `button` and `accordion`.  Allowing class names to directly match components.  When you see `now-` all over css and html it does make life more difficult and even removing `now-` from class names like `now-accordion-item__title` make them that much easier to read.  

I was concerned about styles bleeding out in the past, but if we do follow convention (SMACCS and BEM both have the idea of modifiers) then bleed wont occur.   If people are using another accordion and the styles conflict then I say the style-guide is the source of truth and is the one that matters.  Or, they should only import what they use i.e. not the whole toolkit and not the whole 3rd party library.

This may be controversial and a hard-line to take, but will help keep code shorter and easier to read.  It might sound like it goes against common sense, but I believe it will work and make our lives better in the long run.

**Comment by peter-mouland** [comment]
agreed in meeting to use `n-`
